'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const MAIN_PATH = path.resolve(__dirname, '../../src/main.js')

test('product composition initializes ModelManager before the SQLite application runtime', () => {
  const source = fs.readFileSync(MAIN_PATH, 'utf8')
  const managerIndex = source.indexOf('modelManager = new ModelManager({')
  const initializeIndex = source.indexOf('await modelManager.initialize()', managerIndex)
  const runtimeIndex = source.indexOf('applicationRuntime = new SubtitleApplicationRuntime({', initializeIndex)
  assert.ok(managerIndex >= 0 && initializeIndex > managerIndex && runtimeIndex > initializeIndex)
  assert.match(source, /const externalModelsAllowed = allowsExternalModelResources\(process\.env, \{ packaged: app\.isPackaged \}\)/)
  assert.match(source, /\.\.\.\(externalModelsAllowed\s*\? \{ externalReady:/s)
  assert.match(source, /externalReady:\s*\(artifactId\) => isExternalArtifactReady\(artifactId\)/)
  assert.match(source, /createApprovedRuntimeDefinition\(\{\s*userDataDir: app\.getPath\('userData'\),\s*allowExternal: allowsExternalModelResources\(process\.env, \{ packaged: app\.isPackaged \}\)/s)
  assert.match(source, /await modelManager\.initialize\(\)[\s\S]{0,350}if \(quitRequested\) return false/s)
  assert.match(source, /await applicationRuntime\.start\(\)\s*if \(quitRequested\) return false/s)
})

test('settings-only model IPC separates core install, optional refinement download/cancel, and the global preference', () => {
  const source = fs.readFileSync(MAIN_PATH, 'utf8')
  assert.match(source, /ipcMain\.handle\(CHANNELS\.MODEL_STATUS_GET, \(event\) => \{\s*requireSender\(event, CHANNELS\.MODEL_STATUS_GET\)/s)
  assert.match(source, /ipcMain\.handle\(CHANNELS\.MODEL_INSTALL, \(event\) => \{\s*requireSender\(event, CHANNELS\.MODEL_INSTALL\)\s*return installModelResources\(\)/s)
  assert.match(source, /ipcMain\.handle\(CHANNELS\.MODEL_INSTALL_REFINEMENT, \(event\) => \{\s*requireSender\(event, CHANNELS\.MODEL_INSTALL_REFINEMENT\)\s*return installRefinementModelResources\(\)/s)
  assert.match(source, /ipcMain\.handle\(CHANNELS\.MODEL_CANCEL_INSTALL, \(event\) => \{\s*requireSender\(event, CHANNELS\.MODEL_CANCEL_INSTALL\)\s*return cancelModelInstall\(\)/s)
  assert.match(source, /ipcMain\.handle\(CHANNELS\.REFINEMENT_PREFERENCE_SET, \(event, enabled\) => \{\s*requireSender\(event, CHANNELS\.REFINEMENT_PREFERENCE_SET\)\s*return setRefinementPreference\(enabled\)/s)
  assert.doesNotMatch(source, /ipcMain\.handle\(CHANNELS\.MODEL_INSTALL, \(event,\s*[^)]/)
  assert.doesNotMatch(source, /ipcMain\.handle\(CHANNELS\.MODEL_INSTALL_REFINEMENT, \(event,\s*[^)]/)
  assert.doesNotMatch(source, /ipcMain\.handle\(CHANNELS\.MODEL_CANCEL_INSTALL, \(event,\s*[^)]/)
  assert.match(source, /activateApprovedRuntime\(\{\s*coordinator,\s*userDataDir: app\.getPath\('userData'\),\s*allowExternal: allowsExternalModelResources\(process\.env, \{ packaged: app\.isPackaged \}\),\s*\.\.\.runtimeEvidenceOptions\s*\}\)/s)
  assert.match(source, /installModelResourceGroup\(\(\) => modelManager\.installCore\(\)\)/)
  assert.match(source, /installModelResourceGroup\(\(\) => modelManager\.installRefinement\(\)\)/)
  assert.match(source, /modelManager\.cancelInstall\(\)/)
  assert.match(source, /config\.setRefinementPreference\(enabled === true, modelManager\.isRefinementReady\(\)\)/)
  assert.match(source, /config\.setRefinementPreference\([\s\S]{0,800}coordinator\.updateConfiguration\(config\.get\(\)\)/)
})

test('startup audits the optional refinement readiness without initiating a download and exposes an explicit fallback notice', () => {
  const source = fs.readFileSync(MAIN_PATH, 'utf8')
  const bootstrap = source.slice(source.indexOf('async function bootstrapApplication ()'))

  assert.match(bootstrap, /await modelManager\.initialize\(\)[\s\S]{0,350}config\.reconcileRefinementReadiness\(modelManager\.isRefinementReady\(\)\)/)
  assert.match(source, /let refinementPreferenceFallbackNotice = false/)
  assert.match(source, /refinementPreferenceFallback: refinementPreferenceFallbackNotice/)
  assert.doesNotMatch(bootstrap, /reconcileRefinementReadiness[\s\S]{0,160}install(?:Core|Refinement)?\(/)
})

test('SEM-F00/SEM-F33/J25: model access initializes during bootstrap and is independent of post-session refinement notice', () => {
  const source = fs.readFileSync(MAIN_PATH, 'utf8')
  const bootstrapStart = source.indexOf('async function bootstrapApplication ()')
  const bootstrapEnd = source.indexOf('function cleanupUiRuntime ()', bootstrapStart)
  const bootstrap = source.slice(bootstrapStart, bootstrapEnd)
  const noticeStart = source.indexOf('async function refreshPostSessionRefinementNotice')
  const noticeEnd = source.indexOf('async function runRuntimeCommand', noticeStart)
  const notice = source.slice(noticeStart, noticeEnd)

  assert.match(bootstrap, /await applicationRuntime\.start\(\)[\s\S]*modelAccessRuntime = new ModelAccessRuntime\(/)
  assert.match(bootstrap, /directory: path\.join\(userDataDir, 'agent-model-credentials'\)/)
  assert.doesNotMatch(notice, /CredentialVault|ModelAccessRuntime|RemoteModelCatalogPullController/)
})

test('quit and native-crash diagnostics are wired at the product composition root', () => {
  const source = fs.readFileSync(MAIN_PATH, 'utf8')
  const managerShutdown = source.indexOf('shutdownTasks.push(modelManager.shutdownWithin')
  const storageShutdown = source.indexOf('shutdownTasks.push(applicationRuntime.shutdownWithin', managerShutdown)
  assert.ok(managerShutdown >= 0 && storageShutdown > managerShutdown)
  assert.match(source, /shutdownTasks\.push\(modelManager\.shutdownWithin/)
  assert.match(source, /shutdownTasks\.push\(applicationRuntime\.shutdownWithin/)
  assert.match(source, /await Promise\.allSettled\(shutdownTasks\)/)
  assert.doesNotMatch(source, /await modelManager\.shutdownWithin/)
  assert.doesNotMatch(source, /await applicationRuntime\.shutdownWithin/)
  assert.match(source, /webContents\.on\('render-process-gone'/)
  assert.match(source, /app\.on\('child-process-gone'/)
  assert.match(source, /createMainEvidenceBridge\(\)/)
  assert.match(source, /exitEvidence\.recordRenderProcessGone\(win\.webContents, details\)/)
  assert.match(source, /exitEvidence\.recordChildProcessGone\(details\)/)
  assert.match(source, /exitEvidence\.recordPreloadError\(win\.webContents\)/)
  assert.match(source, /exitEvidence\.recordUnresponsive\(win\.webContents\)/)
  for (const stage of ['main-started', 'app-ready', 'bootstrap-complete', 'quit-requested', 'will-quit']) {
    assert.ok(source.includes(`markLifecycle('${stage}')`), `missing ${stage} evidence`)
  }
  assert.match(source, /registerAudioHostWebContents/)
  assert.match(source, /onAudioHostRenderProcessGone/)
  assert.match(source, /onAudioHostPreloadError/)
  assert.match(source, /onAudioHostUnresponsive/)
  assert.match(source, /onRealtimeUtilityFatal/)
  assert.match(source, /onRefineUtilityFatal/)
  assert.match(source, /onStorageUtilityFatal/)
  assert.match(source, /service=\$\{service\}.+type=\$\{type\}.+reason=\$\{reason\}/)
  assert.match(source, /diagnosticLabel\(details\.serviceName, CHILD_SERVICE_LABELS\)/)
  assert.doesNotMatch(source, /diagnosticLabel\(details\.name/)
  assert.match(source, /win\.on\('unresponsive'/)
  assert.match(source, /webContents\.on\('did-fail-load'/)
})

test('before-quit remains prevented when exact-child shutdown rejects', () => {
  const source = fs.readFileSync(MAIN_PATH, 'utf8')
  const barrierStart = source.indexOf('function beginQuitBarrier (event)')
  const barrierEnd = source.indexOf("const hasSingleInstanceLock = app.requestSingleInstanceLock()", barrierStart)
  const barrier = source.slice(barrierStart, barrierEnd)

  assert.match(barrier, /event\.preventDefault\(\)/)
  assert.match(barrier, /\}\)\(\)\.then\(\(\) => \{[\s\S]*quitBarrierComplete = true[\s\S]*app\.quit\(\)/)
  assert.match(barrier, /\.catch\(\(error\) => \{[\s\S]*quitBarrierPromise = null/)
  assert.doesNotMatch(barrier, /\.finally\([\s\S]*app\.quit\(\)/)
})

test('the ordinary start command uses the exact-child evidence supervisor', () => {
  const packageJson = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../package.json'), 'utf8'))
  assert.equal(packageJson.scripts.start, 'node scripts/run-supervised-electron.js --entry .')
})
